server:
  port: 443
  servlet:
    context-path: /galaxy-sso
  ssl:
    key-store: classpath:galaxy.keystore
    key-store-password: galaxy
    key-alias: galaxy
    key-store-type: JKS

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/galaxy?characterEncoding=utf8&useSSL=true&&serverTimezone=GMT
    username: root
    password: root
  #profiles: dev
  devtools:
    add-properties: false
  banner:
    location: classpath:banner.txt
  quartz:
    job-store-type: jdbc
    auto-startup: true